OnlineBookingWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineBookingWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

OnlineBookingWeb/Controllers/KundeSideController.cs
using SQLConnectionApplication.DataProviders;
using SQLConnectionApplication.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineBookingWeb.Controllers
{
    public class KundeSideController : Controller
    {
        KundeDataprovider kundeDataprovider;
        // GET: KundeSide
        public ActionResult Index(string userName)
        {
            Kunde kunden;
            if (userName != null)
            {
                kundeDataprovider = new KundeDataprovider();
                kunden = kundeDataprovider.FinnKunde(userName);
            }
            else kunden = new Kunde();
            return View(kunden);
        }


    }
}

OnlineBookingWeb/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using OnlineBookingWeb.Services;
using System.Web.Mvc;
using System.Web.Security;

namespace OnlineBookingWeb.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogonUser(string userName, string password)
        {
            var authenticationService = new AuthenticationService();

            if (authenticationService.ValidateUser(userName, password))
            {
                return RedirectToAction("index", "KundeSide", new { userName = userName });
            }
            else return RedirectToAction("index", "Login");
        }
    }
}

OnlineBookingWeb/Controllers/RegistrerController.cs
using SQLConnectionApplication.DataProviders;
using SQLConnectionApplication.Model;
using System;
using System.Web.Mvc;

namespace OnlineBookingWeb.Controllers
{
    public class RegistrerController : Controller
    {
        KundeDataprovider kundeDataprovider;
        // GET: Registrer
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegistrerKunde(string userName, string password)
        {
            kundeDataprovider = new KundeDataprovider();
            if (!(String.IsNullOrWhiteSpace(userName) && String.IsNullOrWhiteSpace(password))){
                Kunde kunde = new Kunde();
                kunde.KundeID = 1;
                kunde.Navn = userName;
                kunde.Passord = password;
                kundeDataprovider.LeggTilKunde(kunde);

                return RedirectToAction("index", "Login");
                
            }
            else return RedirectToAction("index", "Registrer");
        }
    }
}

OnlineBookingWeb/Controllers/ReservasjonStatusController.cs
using SQLConnectionApplication.DataProviders;
using SQLConnectionApplication.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineBookingWeb.Controllers
{
    public class ReservasjonStatusController : Controller
    {
        // GET: ReservasjonStatus
        public ActionResult Index(string userName)

        {
            KundeDataprovider kundeDataprovder = new KundeDataprovider();
            ReservasjonDataprovider reservasjonDataprovider = new ReservasjonDataprovider();

            var reservasjoner = reservasjonDataprovider.FinnAlleReservasjoner().Where(r => r.Kunde.Navn == userName);
            return View(reservasjoner);
        }


    }
}

OnlineBookingWeb/Controllers/RomReservasjonController.cs
using SQLConnectionApplication.DataProviders;
using SQLConnectionApplication.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.ApplicationServices;
using System.Web.Mvc;

namespace OnlineBookingWeb.Controllers
{
	public class RomReservasjonController : Controller
	{
		RomDataprovider romProvider = new RomDataprovider();
		ReservasjonDataprovider reservasjonProvider = new ReservasjonDataprovider();
		KundeDataprovider kundeDataprovider = new KundeDataprovider();
		List<Rom> roms = new List<Rom>();



		// GET: RomReservasjon
		[HttpGet]
		public ActionResult Index(String KundeID)
		{
			var kundeid = Convert.ToInt32(KundeID);
			this.Session["kundeID"] = kundeid;
			System.Diagnostics.Debug.WriteLine(kundeid);
			return View(roms);
		}

		[HttpPost]
		public ActionResult Index(DateTime fdato, DateTime tdato, int storrelse, int kvalitet, int antallsenger)
		{
			var kunde = this.Session["kundeID"];
			this.Session["kundeID"] = kunde;
			this.Session["fraDato"] = fdato;
			this.Session["tilDato"] = tdato;



			var rommene = romProvider.FinnAlleRom();
			//	var reservasjonene = reservasjonProvider.FinnAlleReservasjoner();
			var muligrom = (from rom in rommene
							where gyldigRom(rom.Reservasjoner, fdato, tdato) && gyldigValg(rom, storrelse, kvalitet, antallsenger)
							select rom).ToList();



			roms = (List<Rom>)muligrom;
			return View(muligrom);
		}
		[HttpPost]
		public ActionResult VelgRom(String RomID)
		{
			int romID = Convert.ToInt32(RomID);
			int kundeID = Convert.ToInt32(this.Session["kundeID"]);
			Reservasjon reservasjon = new Reservasjon();
			reservasjon.RomId = romID;
			reservasjon.KundeId = Convert.ToInt32(this.Session["kundeID"]);
			reservasjon.TilDato = Convert.ToDateTime(this.Session["fraDato"]);
			reservasjon.FraDato = Convert.ToDateTime(this.Session["tilDato"]);
			reservasjon.ReservasjonStatus = 0;

			System.Diagnostics.Debug.WriteLine(romID);
			System.Diagnostics.Debug.WriteLine(Convert.ToDateTime(this.Session["fraDato"]));
			System.Diagnostics.Debug.WriteLine(Convert.ToDateTime(this.Session["tilDato"]));

			reservasjonProvider.LeggTilReservasjon(reservasjon);
			return RedirectToAction("Index", "KundeSide", new { userName = kundeDataprovider.FinnKunde(kundeID).Navn });
		}
		public Boolean gyldigValg(Rom rom, int storrelse, int kvalitet, int antallsenger)
		{
			//if (((int) rom.Storrelse > storrelse) && ((int) rom.Kvalitet > kvalitet) && (rom.AntallSenger > antallsenger))
			if (rom.AntallSenger < antallsenger)
			{
				return false;
			}
			if ((int)rom.Storrelse < storrelse)
			{
				return false;
			}
			if ((int)rom.Kvalitet < kvalitet)
			{
				return false;
			}
			return true;

		}
		public Boolean gyldigRom(ICollection<Reservasjon> reservasjons, DateTime fdato, DateTime tdato)
		{
			foreach (Reservasjon reservasjon in reservasjons)
			{
				if ((reservasjon.FraDato >= fdato && reservasjon.FraDato <= tdato) || (reservasjon.TilDato >= fdato && reservasjon.TilDato <= tdato))
				{
					return false;
				}
			}
			return true;
		}
	}

}

OnlineBookingWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OnlineBookingWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineBookingWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Hotel booking system";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

OnlineBookingWeb/Views/KundeSide/index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kundeside</h2>

@if (Model.Navn != null)
{
    <h3>Hei @Model.Navn !</h3>

    <input type="button" value="Gå til romreservasjon" onclick="location.href='@Url.Action("Index", "RomReservasjon",new {kundeId = Model.KundeID})'" />
    <input type="button" value="Se status på reservasjoner" onclick="location.href='@Url.Action("Index", "ReservasjonStatus", new { userName = Model.Navn } )'" />
}

@if (Model.Navn == null)
{
    <h3> Du må gå til innlogging for å se kundeinformasjon</h3>
    <input type="button" value="Gå til innlogging"  onclick="location.href='@Url.Action("Index", "Login")'"/>
}

OnlineBookingWeb/Views/Login/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ 
    ViewBag.Title = "Login page";
}

<h2> Hotel Booking login side</h2>

<div class="container">

    <form action="~/Login/LogonUser" method="post">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="userName" required />

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="password" required />

        <button type="submit">Login</button>
    </form>

    <input type="button" value="Gå til registrering av kunde" onclick="location.href='@Url.Action("Index", "Registrer")'" />

</div>

OnlineBookingWeb/Views/Registrer/index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2> Registrer ny kunde</h2>

<div class="container">

    <form action="~/Registrer/RegistrerKunde" method="post">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="userName" required />

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="password" required />
        <button type="submit">Login</button>
    </form>

</div>

OnlineBookingWeb/Views/ReservasjonStatus/index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User reservation status</h2>
@foreach (var reservasjon in Model)
{
    <div>@reservasjon</div>
}

OnlineBookingWeb/Views/RomReservasjon/index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Rom Reservasjon";
}

@model List<Rom>

<h2>Rom Reservasjon</h2>

<div class="container">
    <form action="~/RomReservasjon/Index" method="post">

        <label for="fradato"><b>Fra Dato:</b></label>
        <input type="date" name="fdato" required />

        <label for="tildato"><b>Til Dato:</b></label>
        <input type="date" name="tdato" required />

        <label for="storrelse"><b>Størrelse:</b></label>
        <select name="storrelse">
            <option value="0">Lite</option>
            <option value="1">Middels</option>
            <option value="2">Stort</option>
        </select>

        <label for="kvalitet"><b>Kvalitet:</b></label>
        <select name="kvalitet">
            <option value="0">Dårlig</option>
            <option value="1">Middels</option>
            <option value="2">Bra</option>
        </select>

        <label for="antallsenger"><b>Antall Senger:</b></label>
        <input type="text" name="antallsenger" required />

        <button type="submit">Finn Rom</button>
    </form>
   <table>
       <tr>
           <th>
               RomNummer
           </th>
       </tr>
        @foreach(var rom in Model)
        {
            <tr>
                <td>@rom</td>
                <td><form action="~/RomReservasjon/VelgRom" method="post">
                    <input type="hidden" name="RomID" value="@rom.RomID" />
                    <button type="submit">Velg rom</button>
                    </form></td>
            </tr>
        }
   </table>

</div>

OnlineBookingWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>